import type { SecretItem } from "../../../lib/type";

export const items_31_to_40: SecretItem[] = [
  {
    floor: 31,
    name: "Phantom Lantern",
    type: "unlockedItems",
    effect: "ghostVisionLevel",
    value: 3,
    description: "Ghosts remain visible permanently.",
  },
  {
    floor: 32,
    name: "Infernal Reach",
    type: "stat",
    effect: "attackRange",
    value: 1,
    description: "Your attacks extend further (+1 Range).",
  },
  {
    floor: 33,
    name: "Last Ember",
    type: "stat",
    effect: "resurectionCount",
    value: 1,
    description: "Revive once upon death.",
  },
  {
    floor: 34,
    name: "Flame Pulse",
    type: "unlockedPassives",
    effect: "AreaDamageOnAttack",
    value: true,
    description: "Deals minor splash damage.",
  },
  {
    floor: 35,
    name: "Magic Key",
    type: "unlockedItems",
    effect: "keyLevel",
    value: 4,
    description: "Opens arcane seals.",
  },
  {
    floor: 36,
    name: "Ancient Roar",
    type: "unlockedPassives",
    effect: "fearLowLevelEnemies",
    value: true,
    description: "Nearby low-level enemies hesitate briefly.",
  },
  {
    floor: 37,
    name: "Mythic Scaleplate",
    type: "stat",
    effect: "hp",
    value: 4,
    description: "Increase maximum HP by 4.",
  },
  {
    floor: 38,
    name: "War Knowledge",
    type: "reducedDamage",
    effect: "royalGuard",
    value: 1,
    description: "Reduces damage from royal guards.",
  },
  {
    floor: 39,
    name: "Dragon's Breath",
    type: "unlockedSkills",
    effect: "fireBreathOncePerFloor",
    value: true,
    description: "Unleash a fiery breath attack once per floor.",
  },
  {
    floor: 40,
    name: "Crimson Wrath",
    type: "stat",
    effect: "attack",
    value: 1,
    description: "Increase attack by 1.",
  },
];
