import type { SecretItem } from "../../../lib/type";

export const items_21_to_30: SecretItem[] = [
  {
    floor: 21,
    name: "True Sight Orb",
    type: "unlockedPassives",
    effect: "canSeeExits",
    value: true,
    description: "Reveals invisible exits.",
  },
  {
    floor: 22,
    name: "Heavy Tail",
    type: "unlockedPassives",
    effect: "canPushEnemiesBehind",
    value: true,
    description: "Enemies behind you are pushed back when you attack.",
  },
  {
    floor: 23,
    name: "Runic Scale",
    type: "reducedDamage",
    effect: "magic",
    value: 1,
    description: "Reduces magic damage taken.",
  },
  {
    floor: 24,
    name: "Smoke Breath",
    type: "unlockedSkills",
    effect: "stunEnemyOncePerFloor",
    value: true,
    description: "Stuns an adjacent enemy for one turn once per floor.",
  },
  {
    floor: 25,
    name: "Silver Key",
    type: "unlockedItems",
    effect: "keyLevel",
    value: 3,
    description: "Opens silver gates.",
  },
  {
    floor: 26,
    name: "Dungeon Map Fragment",
    type: "unlockedPassives",
    effect: "dungeonmapFragment",
    value: true,
    description: "Reveals current room layout.",
  },
  {
    floor: 27,
    name: "Dragonhide",
    type: "stat",
    effect: "hp",
    value: 4,
    description: "Increase maximum HP by 4.",
  },
  {
    floor: 28,
    name: "Elder Scale",
    type: "reducedDamage",
    effect: "physical",
    value: 1,
    description: "Reduces physical damage taken.",
  },
  {
    floor: 29,
    name: "Vengeful Spirit",
    type: "unlockedPassives",
    effect: "damageEnemyOnFirstDamageTakenPerFloor",
    value: true,
    description: "First attacker takes damage.",
  },
  {
    floor: 30,
    name: "Drake Ferocity",
    type: "stat",
    effect: "attack",
    value: 1,
    description: "Increase attack by 1.",
  },
];
