import type { Monster } from "../../../lib/type";

export const ghost: Monster[] = [
  {
    name: "Lost Spirit",
    slug: "lost-spirit",
    monsterFamilly: "ghost",
    isVisible: false,
    difficulty: 14,
    maxHp: 4,
    hp: 4,
    attack: 2,
    attackRange: 2,
    attackWeapon: "magic",
    specialFloor: "haunted",
    facing: "down",
    actionPerTurn: 1,
  },
  {
    name: "Crying Specter",
    slug: "crying-specter",
    monsterFamilly: "ghost",
    isVisible: false,
    difficulty: 22,
    maxHp: 6,
    hp: 6,
    attack: 3,
    attackRange: 3,
    attackWeapon: "magic",
    specialFloor: "haunted",
    facing: "down",
    actionPerTurn: 2,
  },
  {
    name: "Phantom Knight",
    slug: "phantom-knight",
    monsterFamilly: "ghost",
    isVisible: false,
    difficulty: 35,
    maxHp: 10,
    hp: 10,
    attack: 3,
    attackRange: 1,
    attackWeapon: "physical",
    specialFloor: "haunted",
    facing: "down",
    actionPerTurn: 1,
  },
];
