import type { Monster } from "../../../lib/type";

export const livingArmor: Monster[] = [
  {
    name: "Rusty Armor",
    slug: "rusty-armor",
    monsterFamilly: "living armor",
    isVisible: true,
    difficulty: 8,
    maxHp: 8,
    hp: 8,
    attack: 2,
    attackRange: 1,
    attackWeapon: "physical",
    specialFloor: "forge",
    facing: "down",
    actionPerTurn: 1,
  },
  {
    name: "Royal Guard Armor",
    slug: "royal-guard-armor",
    monsterFamilly: "living armor",
    isVisible: true,
    difficulty: 20,
    maxHp: 12,
    hp: 12,
    attack: 3,
    attackRange: 1,
    attackWeapon: "physical",
    specialFloor: "castle",
    facing: "down",
    actionPerTurn: 1,
  },
  {
    name: "Cursed Halberd Armor",
    slug: "cursed-halberd-armor",
    monsterFamilly: "living armor",
    isVisible: true,
    difficulty: 28,
    maxHp: 14,
    hp: 14,
    attack: 4,
    attackRange: 2,
    attackWeapon: "physical",
    specialFloor: "forge",
    facing: "down",
    actionPerTurn: 1,
  },
];
