import type { Monster } from "../../../lib/type";

export const mage: Monster[] = [
  {
    name: "Cult Mage",
    slug: "cult-mage",
    monsterFamilly: "cult",
    isVisible: true,
    difficulty: 12,
    maxHp: 4,
    hp: 4,
    attack: 3,
    attackRange: 4,
    attackWeapon: "magic",
    specialFloor: "arcane",
    facing: "down",
    actionPerTurn: 1,
    attackChargeTurn: 2,
  },
  {
    name: "Arcane Sentinel",
    slug: "arcane-sentinel",
    monsterFamilly: "cult",
    isVisible: true,
    difficulty: 25,
    maxHp: 10,
    hp: 10,
    attack: 3,
    attackRange: 3,
    attackWeapon: "magic",
    specialFloor: "arcane",
    facing: "down",
    actionPerTurn: 2,
    attackChargeTurn: 1,
  },
  {
    name: "Hex Binder",
    slug: "hex-binder",
    monsterFamilly: "cult",
    isVisible: true,
    difficulty: 30,
    maxHp: 6,
    hp: 6,
    attack: 3,
    attackRange: 4,
    attackWeapon: "magic",
    specialFloor: "arcane",
    facing: "down",
    actionPerTurn: 1,
    attackChargeTurn: 2,
  },
];
