import type { Monster } from "../../../lib/type";

export const royalForce: Monster[] = [
  {
    name: "Knight Recruit",
    slug: "knight-recruit",
    monsterFamilly: "royal",
    isVisible: true,
    difficulty: 10,
    maxHp: 6,
    hp: 6,
    attack: 2,
    attackRange: 1,
    attackWeapon: "melee",
    specialFloor: "barracks",
    facing: "down",
    actionPerTurn: 1,
  },
  {
    name: "Royal Archer",
    slug: "royal-archer",
    monsterFamilly: "royal",
    isVisible: true,
    difficulty: 16,
    maxHp: 5,
    hp: 5,
    attack: 3,
    attackRange: 6,
    attackWeapon: "ranged",
    specialFloor: "barracks",
    facing: "down",
    actionPerTurn: 1,
  },
  {
    name: "Royal Spearmaster",
    slug: "royal-spearmaster",
    monsterFamilly: "royal",
    isVisible: true,
    difficulty: 32,
    maxHp: 9,
    hp: 9,
    attack: 3,
    attackRange: 2,
    attackWeapon: "melee",
    specialFloor: "barracks",
    facing: "down",
    actionPerTurn: 2,
  },
  {
    name: "Templar Captain",
    slug: "templar-captain",
    monsterFamilly: "royal",
    isVisible: true,
    difficulty: 47,
    maxHp: 18,
    hp: 18,
    attack: 4,
    attackRange: 1,
    attackWeapon: "melee",
    specialFloor: "castle",
    facing: "down",
    actionPerTurn: 1,
  },
];
