import type { Monster } from "../../../lib/type";

export const slime: Monster[] = [
  {
    name: "Green Slime",
    slug: "green-slime",
    monsterFamilly: "slime",
    isVisible: true,
    difficulty: 1,
    maxHp: 2,
    hp: 2,
    attack: 1,
    attackRange: 1,
    attackWeapon: "melee",
    specialFloor: "slime",
    facing: "down",
    actionPerTurn: 1,
    attackChargeTurn: 0,
  },
  {
    name: "Red Slime",
    slug: "red-slime",
    monsterFamilly: "slime",
    isVisible: true,
    difficulty: 5,
    maxHp: 4,
    hp: 4,
    attack: 2,
    attackRange: 1,
    attackWeapon: "melee",
    specialFloor: "slime",
    facing: "down",
    actionPerTurn: 1,
    attackChargeTurn: 0,
  },
  {
    name: "Crystal Slime",
    slug: "crystal-slime",
    monsterFamilly: "slime",
    isVisible: true,
    difficulty: 15,
    maxHp: 6,
    hp: 6,
    attack: 2,
    attackRange: 1,
    attackWeapon: "melee",
    specialFloor: "slime",
    facing: "down",
    actionPerTurn: 2,
    attackChargeTurn: 0,
  },
  {
    name: "Venom Slime",
    slug: "venom-slime",
    monsterFamilly: "slime",
    isVisible: true,
    difficulty: 18,
    maxHp: 5,
    hp: 5,
    attack: 2,
    attackRange: 1,
    attackWeapon: "melee",
    specialFloor: "slime",
    facing: "down",
    actionPerTurn: 1,
    attackChargeTurn: 0,
  },
];
