import type { Monster } from "../../../lib/type";

export const undead: Monster[] = [
  {
    name: "Skeleton",
    slug: "skeleton",
    monsterFamilly: "undead",
    isVisible: true,
    difficulty: 6,
    maxHp: 5,
    hp: 5,
    attack: 2,
    attackRange: 1,
    attackWeapon: "physical",
    specialFloor: "crypt",
    facing: "down",
    actionPerTurn: 1,
  },
  {
    name: "Wraith",
    slug: "wraith",
    monsterFamilly: "undead",
    isVisible: true,
    difficulty: 18,
    maxHp: 6,
    hp: 6,
    attack: 3,
    attackRange: 2,
    attackWeapon: "magic",
    specialFloor: "crypt",
    facing: "down",
    actionPerTurn: 2,
  },
  {
    name: "Bone Archer",
    slug: "bone-archer",
    monsterFamilly: "undead",
    isVisible: true,
    difficulty: 24,
    maxHp: 5,
    hp: 5,
    attack: 3,
    attackRange: 5,
    attackWeapon: "ranged",
    specialFloor: "crypt",
    facing: "down",
    actionPerTurn: 1,
  },
  {
    name: "Rotting Champion",
    slug: "rotting-champion",
    monsterFamilly: "undead",
    isVisible: true,
    difficulty: 40,
    maxHp: 15,
    hp: 15,
    attack: 4,
    attackRange: 1,
    attackWeapon: "physical",
    specialFloor: "crypt",
    facing: "down",
    actionPerTurn: 1,
  },
];
