import type { Monster } from "../../../lib/type";

export const vermin: Monster[] = [
  {
    name: "Cave Rat",
    slug: "cave-rat",
    monsterFamilly: "vermin",
    isVisible: true,
    difficulty: 3,
    maxHp: 2,
    hp: 2,
    attack: 1,
    attackRange: 1,
    attackWeapon: "melee",
    specialFloor: "rat",
    facing: "down",
    actionPerTurn: 1,
    attackChargeTurn: 0,
    attackChargeTurnMax: 0,
  },
  {
    name: "Shadow Bat",
    slug: "shadow-bat",
    monsterFamilly: "vermin",
    isVisible: true,
    difficulty: 10,
    maxHp: 3,
    hp: 3,
    attack: 1,
    attackRange: 1,
    attackWeapon: "melee",
    specialFloor: "dark",
    facing: "down",
    actionPerTurn: 2,
    attackChargeTurn: 0,
    attackChargeTurnMax: 0,
  },
  {
    name: "Fire Beetle",
    slug: "fire-beetle",
    monsterFamilly: "vermin",
    isVisible: true,
    difficulty: 20,
    maxHp: 4,
    hp: 4,
    attack: 3,
    attackRange: 1,
    attackWeapon: "melee",
    specialFloor: "lava",
    facing: "down",
    actionPerTurn: 1,
    attackChargeTurn: 0,
    attackChargeTurnMax: 0,
  },
  {
    name: "Tunnel Spider",
    slug: "tunnel-spider",
    monsterFamilly: "vermin",
    isVisible: true,
    difficulty: 25,
    maxHp: 6,
    hp: 6,
    attack: 2,
    attackRange: 2,
    attackWeapon: "melee",
    specialFloor: "cave",
    facing: "down",
    actionPerTurn: 1,
    attackChargeTurn: 0,
    attackChargeTurnMax: 0,
  },
];
