import type { SpriteConfig } from "../../lib/type";

export const enemiesSprite: Record<string, SpriteConfig> = {
  "Green Slime": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Red Slime": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Crystal Slime": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Venom Slime": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Cave Rat": {
    sheetSrc: "/Slime.png",
    x: 16,
    y: 0,
    width: 16,
    height: 13,
  },
  "Shadow Bat": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Fire Beetle": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Tunnel Spider": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  Skeleton: {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  Wraith: {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Bone Archer": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Rotting Champion": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Lost Spirit": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Crying Specter": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Phantom Knight": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Rusty Armor": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Royal Guard Armor": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Cursed Halberd Armor": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Cult Mage": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Arcane Sentinel": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Hex Binder": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Knight Recruit": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Royal Archer": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Royal Spearmaster": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
  "Templar Captain": {
    sheetSrc: "/Slime.png",
    x: 0,
    y: 0,
    width: 16,
    height: 13,
  },
};
