import type { SpriteConfig } from "../lib/type";

export const sprites: Record<string, SpriteConfig> = {
  "stairs-down": {
    sheetSrc: "/map_sheet.png",
    x: 128,
    y: 192,
    width: 64,
    height: 64,
  },
  "stairs-up": {
    sheetSrc: "/map_sheet.png",
    x: 192,
    y: 192,
    width: 64,
    height: 64,
  },
  "door-closed": {
    sheetSrc: "/map_sheet.png",
    x: 0,
    y: 256,
    width: 64,
    height: 64,
  },
  "door-open": {
    sheetSrc: "/map_sheet.png",
    x: 0,
    y: 192,
    width: 64,
    height: 64,
  },
  "hint-wall": {
    sheetSrc: "/map_sheet.png",
    x: 0,
    y: 128,
    width: 64,
    height: 64,
  },
  "wall-top": {
    sheetSrc: "/map_sheet.png",
    x: 0,
    y: 0,
    width: 64,
    height: 64,
  },
  "wall-bottom": {
    sheetSrc: "/map_sheet.png",
    x: 0,
    y: 0,
    width: 64,
    height: 64,
  },
  "wall-left": {
    sheetSrc: "/map_sheet.png",
    x: 0,
    y: 0,
    width: 64,
    height: 64,
  },
  "wall-right": {
    sheetSrc: "/map_sheet.png",
    x: 0,
    y: 0,
    width: 64,
    height: 64,
  },
  wall: {
    sheetSrc: "/map_sheet.png",
    x: 0,
    y: 0,
    width: 64,
    height: 64,
  },
  "floor-1": {
    sheetSrc: "/map_sheet.png",
    x: 320,
    y: 64,
    width: 64,
    height: 64,
  },
  "floor-2": {
    sheetSrc: "/map_sheet.png",
    x: 320,
    y: 0,
    width: 64,
    height: 64,
  },
  "floor-3": {
    sheetSrc: "/map_sheet.png",
    x: 320,
    y: 128,
    width: 64,
    height: 64,
  },
  "floor-4": {
    sheetSrc: "/map_sheet.png",
    x: 320,
    y: 192,
    width: 64,
    height: 64,
  },
  "floor-5": {
    sheetSrc: "/map_sheet.png",
    x: 320,
    y: 256,
    width: 64,
    height: 64,
  },
  "chest-closed": {
    sheetSrc: "/map_sheet.png",
    x: 1152,
    y: 256,
    width: 64,
    height: 64,
  },
  "chest-open": {
    sheetSrc: "/map_sheet.png",
    x: 1216,
    y: 256,
    width: 64,
    height: 64,
  },
  "floor-healing": {
    sheetSrc: "/map_sheet.png",
    x: 512,
    y: 192,
    width: 64,
    height: 64,
  },
};
