import type { SpriteConfig } from "../../../lib/type";

export const wallSprites: Record<string, SpriteConfig> = {
  "wall-top": {
    sheetSrc: "/wall_props_32px.png",
    x: 32,
    y: 0,
    width: 32,
    height: 64,
  },
  "wall-bottom": {
    sheetSrc: "/wall_props_32px.png",
    x: 32,
    y: 64,
    width: 32,
    height: 64,
  },
  "wall-left": {
    sheetSrc: "/wall_props_32px.png",
    x: 0,
    y: 32,
    width: 32,
    height: 32,
  },
  "wall-right": {
    sheetSrc: "/wall_props_32px.png",
    x: 64,
    y: 32,
    width: 32,
    height: 32,
  },
  "wall-corner-top-left": {
    sheetSrc: "/wall_props_32px.png",
    x: 0,
    y: 0,
    width: 32,
    height: 64,
  },
  "wall-corner-top-right": {
    sheetSrc: "/wall_props_32px.png",
    x: 64,
    y: 0,
    width: 32,
    height: 64,
  },
  "wall-corner-bottom-left": {
    sheetSrc: "/wall_props_32px.png",
    x: 0,
    y: 64,
    width: 32,
    height: 64,
  },
  "wall-corner-bottom-right": {
    sheetSrc: "/wall_props_32px.png",
    x: 64,
    y: 64,
    width: 32,
    height: 64,
  },
  "wall-isolated": {
    sheetSrc: "/wall_props_32px.png",
    x: 0,
    y: 192,
    width: 32,
    height: 64,
  },
  "wall-dead-end left": {
    sheetSrc: "/wall_props_32px.png",
    x: 0,
    y: 128,
    width: 32,
    height: 64,
  },
  "wall-dead-end right": {
    sheetSrc: "/wall_props_32px.png",
    x: 32,
    y: 128,
    width: 32,
    height: 64,
  },
  "wall-dead-end up": {
    sheetSrc: "/wall_props_32px.png",
    x: 64,
    y: 128,
    width: 32,
    height: 32,
  },
  "wall-dead-end down": {
    sheetSrc: "/wall_props_32px.png",
    x: 64,
    y: 160,
    width: 32,
    height: 64,
  },
  wall: {
    sheetSrc: "/wall_props_32px.png",
    x: 160,
    y: 256,
    width: 32,
    height: 32,
  },
};
