import type { SecretItem } from "../../../../lib/type";

export const items_41_to_50: SecretItem[] = [
  {
    floor: 41,
    name: "War Discipline",
    type: "passive",
    effect: "reduce_enemy_action_speed",
    value: null,
    description: "Enemies act slightly slower.",
  },
  {
    floor: 42,
    name: "Arcane Resistance",
    type: "passive",
    effect: "reduce_magic_damage_further",
    value: null,
    description: "Further reduces magic damage.",
  },
  {
    floor: 43,
    name: "Ethereal Shield",
    type: "passive",
    effect: "no_damage_from_ghosts",
    value: null,
    description: "Negates damage from ghosts.",
  },
  {
    floor: 44,
    name: "Ancient Dominance",
    type: "passive",
    effect: "increase_damage_when_low_hp",
    value: null,
    description: "Deal more damage when wounded.",
  },
  {
    floor: 45,
    name: "Royal Key",
    type: "key",
    effect: "unlock_royal_locks",
    value: null,
    description: "Opens royal locks.",
  },
  {
    floor: 46,
    name: "Runic Barrier",
    type: "passive",
    effect: "absorb_magic_once_per_floor",
    value: null,
    description: "Absorbs one magic hit per floor.",
  },
  {
    floor: 47,
    name: "Sky Sovereign Mark",
    type: "passive",
    effect: "minor_global_damage_bonus",
    value: null,
    description: "Slight increase to all damage dealt.",
  },
  {
    floor: 48,
    name: "Last Ember",
    type: "usable",
    effect: "revive_once",
    value: 1,
    description: "Revive once upon death.",
  },
  {
    floor: 49,
    name: "Titanic Hide",
    type: "stat",
    effect: "hp",
    value: 4,
    description: "Final increase of maximum HP by 4.",
  },
];
