import type { SecretItem } from "../../../../lib/type";

export const items_11_to_20: SecretItem[] = [
  {
    floor: 11,
    name: "Shadow Veil",
    type: "passive",
    effect: "reduce_detection_range",
    value: 1,
    description: "Reduces enemy detection range.",
  },
  {
    floor: 12,
    name: "Soul Claw",
    type: "passive",
    effect: "ghost_damage_normaly",
    value: null,
    description: "Your attacks can damage ghosts normally.",
  },
  {
    floor: 13,
    name: "Forge Ember",
    type: "passive",
    effect: "living_armor_minus_two_hp",
    value: 3,
    description: "Living armors spawn weakened.",
  },
  {
    floor: 14,
    name: "Owl Beak",
    type: "passive",
    effect: "hint_wall_visible",
    value: null,
    description: "Reveals hidden hint walls.",
  },
  {
    floor: 15,
    name: "Iron Key",
    type: "key",
    effect: "unlock_iron_doors",
    value: 2,
    description: "Opens iron gates.",
  },
  {
    floor: 16,
    name: "Ancient Roost",
    type: "passive",
    effect: "heal_on_new_floor",
    value: 2,
    description: "Recover small HP each floor.",
  },
  {
    floor: 17,
    name: "Ancient Carapace",
    type: "stat",
    effect: "hp",
    value: 4,
    description: "Increase maximum HP by 4.",
  },
  {
    floor: 18,
    name: "Wing Guard",
    type: "passive",
    effect: "reduce_ranged_damage",
    value: 1,
    description: "Ranged attacks deal 1 less damage.",
  },
  {
    floor: 19,
    name: "Fang Tempering",
    type: "stat",
    effect: "attack",
    value: 1,
    description: "Increase attack by 1.",
  },
  {
    floor: 20,
    name: "Spectral Eye",
    type: "vision",
    effect: "reveal_ghosts",
    value: 2,
    description: "Allows you to see ghost enemies in the room.",
  },
];
