import type { SecretItem } from "../../../../lib/type";

export const items_41_to_50: SecretItem[] = [
  {
    floor: 41,
    name: "War Discipline",
    type: "unlockedPassives",
    effect: "reduceEnemyActionSpeed",
    value: 1,
    description: "Enemies act slightly slower.",
  },
  {
    floor: 42,
    name: "Arcane Resistance",
    type: "reducedDamage",
    effect: "magic",
    value: 1,
    description: "Further reduces magic damage.",
  },
  {
    floor: 43,
    name: "Ethereal Scales",
    type: "unlockedPassives",
    effect: "ghostDamageNegation",
    value: null,
    description: "Negates damage from ghosts.",
  },
  {
    floor: 44,
    name: "Ancient Dominance",
    type: "unlockedPassives",
    effect: "extraDamageWhenLowHp",
    value: null,
    description: "Deal more damage when wounded.",
  },
  {
    floor: 45,
    name: "Royal Key",
    type: "unlockedItems",
    effect: "keyLevel",
    value: 5,
    description: "Opens royal locks.",
  },
  {
    floor: 46,
    name: "Runic Barrier",
    type: "unlockedPassives",
    effect: "negateMagicOncePerFloor",
    value: null,
    description: "Absorbs one magic hit per floor.",
  },
  {
    floor: 47,
    name: "Sky Sovereign Mark",
    type: "stat",
    effect: "attack",
    value: 1,
    description: "Increase attack by 1.",
  },
  {
    floor: 48,
    name: "Phoenix Feather",
    type: "stat",
    effect: "resurectionCount",
    value: 1,
    description: "Revive once upon death.",
  },
  {
    floor: 49,
    name: "Titanic Hide",
    type: "stat",
    effect: "hp",
    value: 4,
    description: "Final increase of maximum HP by 4.",
  },
];
