import type { SecretItem } from "../../../../lib/type";

export const items_31_to_40: SecretItem[] = [
  {
    floor: 31,
    name: "Phantom Lantern",
    type: "vision",
    effect: "ghosts_always_visible",
    value: 3,
    description: "Ghosts remain visible permanently.",
  },
  {
    floor: 32,
    name: "Infernal Reach",
    type: "stat",
    effect: "range",
    value: 1,
    description: "Your attacks extend further (+1 Range).",
  },
  {
    floor: 33,
    name: "Last Ember",
    type: "usable",
    effect: "revive_once",
    value: 1,
    description: "Revive once upon death.",
  },
  {
    floor: 34,
    name: "Flame Pulse",
    type: "passive",
    effect: "minor_area_damage_on_hit",
    value: 1,
    description: "Deals minor splash damage.",
  },
  {
    floor: 35,
    name: "Magic Key",
    type: "key",
    effect: "unlock_arcane_seals",
    value: 4,
    description: "Opens arcane seals.",
  },
  {
    floor: 36,
    name: "Ancient Roar",
    type: "passive",
    effect: "fear_adjacent_low_level_enemies",
    value: null,
    description: "Nearby low-level enemies hesitate briefly.",
  },
  {
    floor: 37,
    name: "Mythic Scaleplate",
    type: "stat",
    effect: "hp",
    value: 4,
    description: "Increase maximum HP by 4.",
  },
  {
    floor: 38,
    name: "War Knowledge",
    type: "passive",
    effect: "reduce_royal_guard_damage",
    value: 1,
    description: "Reduces damage from royal guards.",
  },
  {
    floor: 39,
    name: "Dragon's Breath",
    type: "usable",
    effect: "fire_breath_attack_once_per_floor",
    value: 3,
    description: "Unleash a fiery breath attack once per floor.",
  },
  {
    floor: 40,
    name: "Crimson Wrath",
    type: "stat",
    effect: "attack",
    value: 1,
    description: "Increase attack by 1.",
  },
];
