import type { SecretItem } from "../../../../lib/type";

export const items_1_to_10: SecretItem[] = [
  {
    floor: 1,
    name: "Ghostly Shroud",
    type: "passive",
    effect: "reduce_ghost_damage",
    value: null,
    description: "Reduces damage taken from ghosts.",
  },
  {
    floor: 2,
    name: "Spectral Lantern",
    type: "usable",
    effect: "reveal_ghosts",
    value: null,
    description: "Reveals all ghosts in the current room.",
  },
  {
    floor: 3,
    name: "Bone Charm",
    type: "passive",
    effect: "chance_to_avoid_death_once",
    value: null,
    description: "Chance to avoid death once.",
  },
  {
    floor: 4,
    name: "Ancient Carapace",
    type: "stat",
    effect: "hp",
    value: 4,
    description: "Increase maximum HP by 4.",
  },
  {
    floor: 5,
    name: "Rust Key",
    type: "key",
    effect: "unlock_basic_doors",
    value: null,
    description: "Opens basic locked doors.",
  },
  {
    floor: 6,
    name: "Empty Chest",
    type: "passive",
    effect: "no_effect",
    value: null,
    description: "An empty chest, who stole its contents?",
  },
  {
    floor: 7,
    name: "Vermin's Bane",
    type: "passive",
    effect: "reduce_vermin_damage",
    value: null,
    description: "Reduces damage taken from vermin.",
  },
  {
    floor: 8,
    name: "Claw Sharpening",
    type: "stat",
    effect: "attack",
    value: 1,
    description: "Increase attack by 1.",
  },

  {
    floor: 10,
    name: "Hardened Scales",
    type: "passive",
    effect: "reduce_damage_once_per_floor",
    value: null,
    description: "Negates first damage taken each floor.",
  },
];
