import type { SecretItem } from "../../../../lib/type";

export const items_21_to_30: SecretItem[] = [
  {
    floor: 21,
    name: "True Sight Orb",
    type: "vision",
    effect: "reveal_exit",
    value: null,
    description: "Reveals invisible exits.",
  },
  {
    floor: 22,
    name: "Heavy Tail",
    type: "passive",
    effect: "push_enemy_back_behind",
    value: null,
    description: "Enemies behind you are pushed back when you attack.",
  },
  {
    floor: 23,
    name: "Runic Scale",
    type: "passive",
    effect: "reduce_magic_damage",
    value: 1,
    description: "Reduces magic damage taken.",
  },
  {
    floor: 24,
    name: "Smoke Breath",
    type: "usable",
    effect: "stun_adjacent_enemy_once_per_floor",
    value: 1,
    description: "Stuns an adjacent enemy for one turn once per floor.",
  },
  {
    floor: 25,
    name: "Silver Key",
    type: "key",
    effect: "unlock_silver_doors",
    value: 3,
    description: "Opens silver gates.",
  },
  {
    floor: 26,
    name: "Dungeon Map Fragment",
    type: "passive",
    effect: "show_room_layout",
    value: null,
    description: "Reveals current room layout.",
  },
  {
    floor: 27,
    name: "Dragonhide",
    type: "stat",
    effect: "hp",
    value: 4,
    description: "Increase maximum HP by 4.",
  },
  {
    floor: 28,
    name: "Elder Scale",
    type: "passive",
    effect: "reduce_physical_damage",
    value: 1,
    description: "Reduces physical damage taken.",
  },
  {
    floor: 29,
    name: "Vengeful Spirit",
    type: "passive",
    effect: "damage_attacker_once",
    value: 3,
    description: "First attacker takes damage.",
  },
  {
    floor: 30,
    name: "Drake Ferocity",
    type: "stat",
    effect: "attack",
    value: 1,
    description: "Increase attack by 1.",
  },
];
