import type { SecretItem } from "../../../../lib/type";

export const items_31_to_40: SecretItem[] = [
  {
    floor: 31,
    name: "Phantom Lantern",
    type: "passive",
    effect: "ghosts_always_visible",
    value: null,
    description: "Ghosts remain visible permanently.",
  },
  {
    floor: 32,
    name: "Infernal Reach",
    type: "stat",
    effect: "range",
    value: 1,
    description: "Your attacks extend further (+1 Range).",
  },
  {
    floor: 33,
    name: "Last Ember",
    type: "usable",
    effect: "revive_once",
    value: 1,
    description: "Revive once upon death.",
  },
  {
    floor: 34,
    name: "Flame Pulse",
    type: "passive",
    effect: "minor_area_damage_on_hit",
    value: null,
    description: "Deals minor splash damage.",
  },
  {
    floor: 35,
    name: "Ancient Roar",
    type: "passive",
    effect: "fear_adjacent_enemies",
    value: null,
    description: "Nearby enemies hesitate briefly.",
  },
  {
    floor: 36,
    name: "Magic Key",
    type: "key",
    effect: "unlock_arcane_seals",
    value: null,
    description: "Opens arcane seals.",
  },
  {
    floor: 37,
    name: "Mythic Scaleplate",
    type: "stat",
    effect: "hp",
    value: 4,
    description: "Increase maximum HP by 4.",
  },
  {
    floor: 38,
    name: "Deep Breath",
    type: "passive",
    effect: "shield_duration_plus_one",
    value: null,
    description: "Shield lasts longer.",
  },
  {
    floor: 39,
    name: "Predator Aura",
    type: "passive",
    effect: "intimidate_weaker_enemies",
    value: null,
    description: "Weaker enemies hesitate to engage.",
  },
  {
    floor: 40,
    name: "Crimson Wrath",
    type: "stat",
    effect: "attack",
    value: 1,
    description: "Increase attack by 1.",
  },
];
