import type { SecretItem } from "../../../../lib/type";

export const items_11_to_20: SecretItem[] = [
  {
    floor: 11,
    name: "Shadow Veil",
    type: "unlockedItems",
    effect: "reducedDetection",
    value: 1,
    description: "Reduces enemy detection range.",
  },
  {
    floor: 12,
    name: "Soul Claw",
    type: "unlockedSkills",
    effect: "normalDamageToGhosts",
    value: null,
    description: "Your attacks can damage ghosts normally.",
  },
  {
    floor: 13,
    name: "Forge Ember",
    type: "reducedDamage",
    effect: "livingArmor",
    value: 1,
    description: "Reduces damage taken from armored enemies.",
  },
  {
    floor: 14,
    name: "Owl Beak",
    type: "unlockedItems",
    effect: "canSeeHintWalls",
    value: null,
    description: "Reveals hidden hint walls.",
  },
  {
    floor: 15,
    name: "Iron Key",
    type: "unlockedItems",
    effect: "keyLevel",
    value: 2,
    description: "Opens iron gates.",
  },
  {
    floor: 16,
    name: "Ancient Roost",
    type: "unlockedItems",
    effect: "moreHealFromSanctuary",
    value: 5,
    description: "Recover small HP each floor.",
  },
  {
    floor: 17,
    name: "Ancient Carapace",
    type: "stat",
    effect: "hp",
    value: 4,
    description: "Increase maximum HP by 4.",
  },
  {
    floor: 18,
    name: "Wing Guard",
    type: "reducedDamage",
    effect: "ranged",
    value: 1,
    description: "Ranged attacks deal 1 less damage.",
  },
  {
    floor: 19,
    name: "Fang Tempering",
    type: "stat",
    effect: "attack",
    value: 1,
    description: "Increase attack by 1.",
  },
  {
    floor: 20,
    name: "Spectral Eye",
    type: "unlockedItems",
    effect: "ghostVisionLevel",
    value: 2,
    description: "Allows you to see ghost enemies in the room.",
  },
];
